# Generated by Django 4.1.5 on 2023-09-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_questionaire', '0002_auto_20230910_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_questionaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
